package com.zcsy.vehicleChargeDriveInfo.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table vehicle_charge_drive_info
 */
public class vehicleChargeDriveInfo extends vehicleChargeDriveInfoKey {
    /**
     * Database Column Remarks:
     *   开始经纬度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_charge_drive_info.begin_lat_lon
     *
     * @mbg.generated Wed Sep 12 15:26:10 CST 2018
     */
    private String beginLatLon;

    /**
     * Database Column Remarks:
     *   开始经纬度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_charge_drive_info.end_lat_lon
     *
     * @mbg.generated Wed Sep 12 15:26:10 CST 2018
     */
    private String endLatLon;

    /**
     * Database Column Remarks:
     *   充电开始SOC
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_charge_drive_info.begin_soc
     *
     * @mbg.generated Wed Sep 12 15:26:10 CST 2018
     */
    private Integer beginSoc;

    /**
     * Database Column Remarks:
     *   充电结束SOC
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_charge_drive_info.end_soc
     *
     * @mbg.generated Wed Sep 12 15:26:10 CST 2018
     */
    private Integer endSoc;

    /**
     * Database Column Remarks:
     *   单次行驶里程-单位（m）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_charge_drive_info.distance
     *
     * @mbg.generated Wed Sep 12 15:26:10 CST 2018
     */
    private Double distance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_charge_drive_info.begin_lat_lon
     *
     * @return the value of vehicle_charge_drive_info.begin_lat_lon
     *
     * @mbg.generated Wed Sep 12 15:26:10 CST 2018
     */
    public String getBeginLatLon() {
        return beginLatLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_charge_drive_info.begin_lat_lon
     *
     * @param beginLatLon the value for vehicle_charge_drive_info.begin_lat_lon
     *
     * @mbg.generated Wed Sep 12 15:26:10 CST 2018
     */
    public void setBeginLatLon(String beginLatLon) {
        this.beginLatLon = beginLatLon == null ? null : beginLatLon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_charge_drive_info.end_lat_lon
     *
     * @return the value of vehicle_charge_drive_info.end_lat_lon
     *
     * @mbg.generated Wed Sep 12 15:26:10 CST 2018
     */
    public String getEndLatLon() {
        return endLatLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_charge_drive_info.end_lat_lon
     *
     * @param endLatLon the value for vehicle_charge_drive_info.end_lat_lon
     *
     * @mbg.generated Wed Sep 12 15:26:10 CST 2018
     */
    public void setEndLatLon(String endLatLon) {
        this.endLatLon = endLatLon == null ? null : endLatLon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_charge_drive_info.begin_soc
     *
     * @return the value of vehicle_charge_drive_info.begin_soc
     *
     * @mbg.generated Wed Sep 12 15:26:10 CST 2018
     */
    public Integer getBeginSoc() {
        return beginSoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_charge_drive_info.begin_soc
     *
     * @param beginSoc the value for vehicle_charge_drive_info.begin_soc
     *
     * @mbg.generated Wed Sep 12 15:26:10 CST 2018
     */
    public void setBeginSoc(Integer beginSoc) {
        this.beginSoc = beginSoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_charge_drive_info.end_soc
     *
     * @return the value of vehicle_charge_drive_info.end_soc
     *
     * @mbg.generated Wed Sep 12 15:26:10 CST 2018
     */
    public Integer getEndSoc() {
        return endSoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_charge_drive_info.end_soc
     *
     * @param endSoc the value for vehicle_charge_drive_info.end_soc
     *
     * @mbg.generated Wed Sep 12 15:26:10 CST 2018
     */
    public void setEndSoc(Integer endSoc) {
        this.endSoc = endSoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_charge_drive_info.distance
     *
     * @return the value of vehicle_charge_drive_info.distance
     *
     * @mbg.generated Wed Sep 12 15:26:10 CST 2018
     */
    public Double getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_charge_drive_info.distance
     *
     * @param distance the value for vehicle_charge_drive_info.distance
     *
     * @mbg.generated Wed Sep 12 15:26:10 CST 2018
     */
    public void setDistance(Double distance) {
        this.distance = distance;
    }
}