package com.zcsy.vehicleChargeDriveInfo.dao;

import com.zcsy.vehicleChargeDriveInfo.model.vehicleChargeDriveInfo;
import com.zcsy.vehicleChargeDriveInfo.model.vehicleChargeDriveInfoKey;

public interface vehicleChargeDriveInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_charge_drive_info
     *
     * @mbg.generated Wed Sep 12 15:26:10 CST 2018
     */
    int deleteByPrimaryKey(vehicleChargeDriveInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_charge_drive_info
     *
     * @mbg.generated Wed Sep 12 15:26:10 CST 2018
     */
    int insert(vehicleChargeDriveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_charge_drive_info
     *
     * @mbg.generated Wed Sep 12 15:26:10 CST 2018
     */
    int insertSelective(vehicleChargeDriveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_charge_drive_info
     *
     * @mbg.generated Wed Sep 12 15:26:10 CST 2018
     */
    vehicleChargeDriveInfo selectByPrimaryKey(vehicleChargeDriveInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_charge_drive_info
     *
     * @mbg.generated Wed Sep 12 15:26:10 CST 2018
     */
    int updateByPrimaryKeySelective(vehicleChargeDriveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_charge_drive_info
     *
     * @mbg.generated Wed Sep 12 15:26:10 CST 2018
     */
    int updateByPrimaryKey(vehicleChargeDriveInfo record);
}